### ISSUE TITLE
Nav pills doesn't work

### ISSUE THREAD

**Issue by SrGiiL** [creativetimofficial/ct-soft-ui-dashboard-pro#12]
Hi, thanks for your help.

I have one problem to add nav pills in my project, it doesn't work great, the active background don't print.
![image](https://user-images.githubusercontent.com/36150625/129249343-dd3bcea2-fbad-4968-a234-27747d47149a.png)

I'm using react and bootstrapJS file is added.

This is the HTML code like a example of docs:
```

        <div class="nav-wrapper position-relative end-0">
          <ul class="nav nav-pills nav-fill p-1" role="tablist">
            <li class="nav-item">
              <a
                class="nav-link mb-0 px-0 py-1 active"
                data-bs-toggle="tab"
                href="#profile-tabs-simple"
                role="tab"
                aria-controls="profile"
                aria-selected="true"
              >
                My Profile
              </a>
            </li>
            <li class="nav-item">
              <a
                class="nav-link mb-0 px-0 py-1"
                data-bs-toggle="tab"
                href="#dashboard-tabs-simple"
                role="tab"
                aria-controls="dashboard"
                aria-selected="false"
              >
                Dashboard
              </a>
            </li>
          </ul>
        </div>

**Comment by groovemen** [comment]
Hello @SrGiiL,

Thank you for using our products, you have to use and integrate the JS function `initNavs()` to initialize the **nav-tabs**. 
Hope this information helps you. Please let us know if we can help you with anything else.

All the best,
Stefan
