### ISSUE TITLE
[Bug] Side Navigation Scroll Expand too Long

### ISSUE THREAD

**Issue by khoer26** [creativetimofficial/ct-soft-ui-dashboard-pro#16]
### Version
1.0.3
### Reproduction link
https://demos.creative-tim.com/soft-ui-dashboard-pro/pages/dashboards/default.html
### Operating System
Windows
### Device
ASUS X441U
### Browser & Version
Chrome Latest
### Steps to reproduce
1. Open at least one pages menu
2. Scroll to bottom
3. There is expanded space
### What is expected?
There is no expanded space
### What is actually happening?
There has expanded space

---

**Comment by rarestoma** [comment]
Hi @khoer26,

Thank you for working with our products.

Can you please send me a video so I can understand better what happens and fix this issue?

Thank you,
Rares

**Comment by khoer26** [comment]
Thanks for your response
 
Here is video attachment for this problem
 
Thank you,
Khoer

https://user-images.githubusercontent.com/60177355/131861643-2a457fa1-0324-4eff-a766-4bc2ffd48d25.mp4

**Comment by rayhanmhd123** [comment]
Hi @rarestoma,

Do you understand what is meant?

Thank you,
Best regards
Muhammad Rayhan
