### ISSUE TITLE
Build project

### ISSUE THREAD

**Issue by carlosamigos** [creativetimofficial/ct-soft-ui-dashboard-pro#17]
Hi,

How do you recommend building the product for production? I'm planning to upload this project to an AWS S3 bucket that will host the webpage. How should I package the project?

Many thanks

**Comment by groovemen** [comment]
Hello @carlosamigos,

Thank you for using our products, you can find more information about how can you upload your project archive on AWS, right here: https://docs.aws.amazon.com/amazonglacier/latest/dev/uploading-an-archive.html 
Hope this infos helps you. Please let us know if we can help you with anything else.

All the best,
Stefan
