### ISSUE TITLE
[Bug] Can't find Gulp

### ISSUE THREAD

**Issue by htorres00** [creativetimofficial/ct-soft-ui-dashboard-pro#2]
### Version
1.0.1
### Reproduction link
https://demos.creative-tim.com/soft-ui-dashboard-pro/pages/dashboards/default.html
### Operating System
MacOs 11.4
### Device
Macbook Pro 2020
### Browser & Version
Visual Studio May 2021
### Steps to reproduce
1. Downloaded zip file and unzip it
2. Installed the latest version of Node and RPM (16.3 and 7.17)
3. CD to the folder with the code (soft-dashboard-pro-html-v1.0.1)
4. typed code .
5. From the terminal typed: rpm install and got this message:
up to date, audited 608 packages in 2s
14 packages are looking for funding
  run `npm fund` for details
14 vulnerabilities (5 low, 5 moderate, 4 high)
To address issues that do not require attention, run:
  npm audit fix
To address all issues (including breaking changes), run:
  npm audit fix --force
6. And I get a long list of errors. Here's the first and last lines:
Mac] > ➜  soft-dashboard-pro-html-v1.0.1 sudo npm audit fix --force
npm WARN using --force Recommended protections disabled.
npm WARN audit Updating gulp to 3.9.1,which is a SemVer major change.
npm WARN audit Updating gulp-sass to 2.3.2,which is a SemVer major change.
npm WARN audit Updating gulp-autoprefixer to 6.1.0,which is a SemVer major change.
npm WARN deprecated natives@1.1.6: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.
...
...
...
...
pm ERR! ../src/binding.cpp:32:16: note: in instantiation of member function 'CallbackBridge<Sass_Value *, void *>::operator()' requested here
npm ERR!   return bridge(argv);
npm ERR!                ^
npm ERR! ../../nan/nan.h:1741:3: note: 'Call' has been explicitly marked deprecated here
npm ERR!   NAN_DEPRECATED inline v8::Local<v8::Value>
npm ERR!   ^
npm ERR! ../../nan/nan.h:106:40: note: expanded from macro 'NAN_DEPRECATED'
npm ERR! # define NAN_DEPRECATED __attribute__((deprecated))
npm ERR!                                        ^
npm ERR! 6 warnings and 1 error generated.
npm ERR! make: *** [Release/obj.target/binding/src/binding.o] Error 1
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/Users/hector/Dropbox/Businesses/upwork/Josh Canova - ScaleUp/soft-dashboard-pro-html-v1.0.1/node_modules/node-gyp/lib/build.js:262:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:394:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp ERR! System Darwin 20.5.0
npm ERR! gyp ERR! command "/usr/local/bin/node" "/Users/hector/Dropbox/Businesses/upwork/Josh Canova - ScaleUp/soft-dashboard-pro-html-v1.0.1/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd /Users/hector/Dropbox/Businesses/upwork/Josh Canova - ScaleUp/soft-dashboard-pro-html-v1.0.1/node_modules/node-sass
npm ERR! gyp ERR! node -v v16.3.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok 
npm ERR! Build failed

I tried with 'sudo' and got the same results. 

*If I run this command from my home dir, it shows this:
[Mac] > ➜  ~ sudo npm audit fix
up to date, audited 8 packages in 615ms
found 0 vulnerabilities
### What is expected?
to not see a long list of errors.
### What is actually happening?
gulp is not found.

---
### Additional comments
I'm installing this in a local environment.

**Comment by rarestoma** [comment]
Hi @htorres00,

Thank you for working with our products and sorry for our late response.

I just tried now running `"npm install"` and everything works as expected. 

Can you please tell me what versions of `npm` are you using?

Thank you,
Rares

**Comment by htorres00** [comment]
NPM version 7.17.0 
Attached is the full log file with the errors I get when I run `npm update`

[2021-07-05T16_25_51_795Z-debug.log](https://github.com/creativetimofficial/ct-soft-ui-dashboard-pro/files/6765485/2021-07-05T16_25_51_795Z-debug.log)

**Comment by rarestoma** [comment]
Hi @htorres00,

I tested using npm v6.14.12 and it works fine. Can you please test it again using this version of npm?

Best regards,
Rares
