### ISSUE TITLE
[Bug] Double scrollbar in side navigation

### ISSUE THREAD

**Issue by jiarenlow95** [creativetimofficial/ct-soft-ui-dashboard-pro#23]
### Version
1.0.4
### Reproduction link
https://demos.creative-tim.com/soft-ui-dashboard-pro/pages/dashboards/default.html
### Operating System
Window
### Device
PC
### Browser & Version
Google Chrome Version 94.0.4606.81 
### Steps to reproduce
1. Open up multiple menu in the side navigation
2. Scroll to bottom
3. Double scrollbar is shown
### What is expected?
Remove the double scrollbar
### What is actually happening?
Double scrollbar is showing up and cause the view of the side menu not showing correctly (some items are covered)

---
### Additional comments
Please help to fix it ASAP, Thanks
Image shows the double scrollbar
![soft-ui-side-navigation-bug](https://user-images.githubusercontent.com/71661041/137371689-f6c36729-7413-497a-98f3-7a55ef47cca9.PNG)

**Comment by jiarenlow95** [comment]
Hi @rarestoma,
Can I know if my reported issue has been resolved? Since it has been a month already the issue is still open.

**Comment by rarestoma** [comment]
Hi @jiarenlow95,

Sorry for our late response.

We made some research and we found out that you have to remove `max-height-vh-100` class from the `collapse navbar-collapse`.

Please let me know if it works.

Best regards,
Rares

**Comment by jiarenlow95** [comment]
Hi,
Thanks for the email and advice.
I have tried to remove max-height-vh-100 class from the collapse
navbar-collapse. (in the main navbar).
It is still the same.
FYI, it happens only if the nav bar contains many menu items.
I open up the menu items, it goes crazy when 35 items show up in the navbar.

Best regards,
Jia Ren

**Comment by rarestoma** [comment]
Hi @jiarenlow95,

Can you please remove also the `h-100` class and see if it works?

If it still not working, can you please help me a video to see exactly how it is working on your side?

Thank you,
Rares

**Comment by jiarenlow95** [comment]
Hi  Rares,
Thanks for your email and sorry for the late reply.
I have tried to remove the h-100 class but it has become worse.

Kindly find attachment for the videos I captured. One of the video shows
before the h-100 class is removed and another one shows after the h-100
class is removed.
You can see the scrollbar goes crazy in the navbar.

 VID_Before_Remove_H-100.mp4
<https://drive.google.com/file/d/1z9tGqHJ1pA0dpzJ19VuRiqt9Ak7wG8Y6/view?usp=drive_web>
 VID_Remove_H-100.mp4
<https://drive.google.com/file/d/1KDez1EP_zr8SAm-8ZpkKiD3DYsnrKCbH/view?usp=drive_web>

Best regards,
Jia Ren

**Comment by rarestoma** [comment]
Hi @jiarenlow95,

I just requested now access to the google drive files.

Thank you,
Rares

**Comment by jiarenlow95** [comment]
Hi Rares,
I have accepted your request, are you able to view the videos now?

**Comment by rarestoma** [comment]
Hi @jiarenlow95,

Yes, now I have access, I will check them and continue doing tests to see what happens.

Thank you,
Rares

**Comment by jiarenlow95** [comment]
Hi Rares,
Great, thanks!

**Comment by rarestoma** [comment]
Hi @jiarenlow95,

We just updated Soft UI Dashboard PRO to v1.0.5 and we also fixed the double scrollbar issue. Can you please check now the newest version and let me know if it works?

Thank you,
Rares

**Comment by jiarenlow95** [comment]
Hi Rares,
Yes, it works for me with the new version of Soft UI Dashboard PRO.
Thanks a lot!!
Have a nice day~

Best regards,
Jia Ren
