### ISSUE TITLE
[Feature Request] Figma files

### ISSUE THREAD

**Issue by gnikolaev** [creativetimofficial/ct-soft-ui-dashboard-pro#26]
### What is your enhancement?
Are there any Figma files available with the theme as I can't seem to find them.

**Comment by rarestoma** [comment]
Hi @gnikolaev,

Thank you for your interest in working with our products.

Unfortunately, Soft UI Dashboard PRO doesn't contain Figma files. I will add it to the discussion for the next updates.

Best regards,
Rares
