### ISSUE TITLE
why don't solve the sidebar problem?

### ISSUE THREAD

**Issue by kamcert** [creativetimofficial/ct-soft-ui-dashboard-pro#27]
<img width="291" alt="1111" src="https://user-images.githubusercontent.com/86335006/142027052-3517bb5a-6b66-4a49-9b5f-e0c90741d471.png">

**Comment by groovemen** [comment]
Hello @kamcert,

Thank you for using our products, by setting z-index: 9999; will solve this problem. Please make sure that you have recompile the SCSS after you have made the changes.
<img width="168" alt="Screenshot 2021-11-17 at 09 40 50" src="https://user-images.githubusercontent.com/21063398/142156848-bcd4e342-ff6a-4da9-98f8-3cc4685f6205.png">

All the best, 
Stefan
