### ISSUE TITLE
f

### ISSUE THREAD

**Issue by kamcert** [creativetimofficial/ct-soft-ui-dashboard-pro#28]

**Comment by kamcert** [comment]
Why can't we solve the problem of overlapping side bars and nav bars?
case1
It's still the same on the me themebootstrap.com.
case2
I updated it to the latest version, but the same phenomenon.
case3
Changing the z-index of sidenav from soft-ui-dashboard.css to 9999 does not solve it.
case4
navbar-vertical.Changing the z-index of sidenav to 9999 in scss does not solve it

**Comment by groovemen** [comment]
Hello @kamcert,

Thank you for using our products, by setting z-index: 9999; will solve this problem. Please make sure that you have recompile the SCSS after you have made the changes.
<img width="238" alt="Screenshot 2021-11-17 at 09 42 24" src="https://user-images.githubusercontent.com/21063398/142157063-dc002178-281a-4d78-bfdf-47d3ad9a6e40.png">

All the best, 
Stefan
