### ISSUE TITLE
Wizard with React

### ISSUE THREAD

**Issue by SrGiiL** [creativetimofficial/ct-soft-ui-dashboard-pro#3]
Hi,

I have one problem using wizard with React, script actions don't apply in navSteps (change of steps)

I have embedded `<script src =" ../../ assets / js / plugins / multistep-form.js "> </script>` in the `index.html` and it doesn't work.

**Comment by SrGiiL** [comment]
Yes, I get some error.

I import the script into the component as follows `import "../../../assets/js/plugins/multistep-form";` and it doesn't work.
![image](https://user-images.githubusercontent.com/36150625/122944720-588b6a00-d378-11eb-9caa-738b9b882204.png)
Buttons don't work.


With react-bootstrap-wizard dependency the styles don't work correctly.
![image](https://user-images.githubusercontent.com/36150625/122944339-08140c80-d378-11eb-9064-62eaf1adce38.png)

Which is the correct form to add the script into a React component?

**Comment by rarestoma** [comment]
Hi @SrGiiL,

Unfortunately, the style for react-bootstrap-wizard will not work properly as the design is made just for the HTML wizard.

Here I found a topic on how to add scripts in React: https://stackoverflow.com/questions/34424845/adding-script-tag-to-react-jsx.

Our team is also working on the React version of Soft UI Dashboard PRO and I hope we will launch it in about 1-2 months.

Best regards,
Rares

**Comment by SrGiiL** [comment]
It worked fine for me, thanks
