### ISSUE TITLE
[Bug] Several scss errors

### ISSUE THREAD

**Issue by krebbi** [creativetimofficial/ct-soft-ui-dashboard-pro#30]
### Version
1.0.4
### Reproduction link
http://www.notavailable.com
### Operating System
linux
### Device
all
### Browser & Version
n/a
### Steps to reproduce
@import "variables"; missing in theme.scss

Module not found: Error: Can't resolve './images/layers.png' in 'resources/sass/soft-ui-dashboard/plugins/pro/_leaflet.scss'
Module not found: Error: Can't resolve './images/layers-2x.png' in 'resources/sass/soft-ui-dashboard/plugins/pro/_leaflet.scss'
Module not found: Error: Can't resolve './images/marker-icon.png' in 'resources/sass/soft-ui-dashboard/plugins/pro/_leaflet.scss'
### What is expected?
compiling
### What is actually happening?
not compiling

---

**Comment by rarestoma** [comment]
Hi @krebbi,

Thank you for working with our products.

Can you please tell me if you modified something in the original theme?

Thank you,
Rares

**Comment by krebbi** [comment]
Hi Rares,

I downloaded the zip and integrated it into my laravel project. 
![Bildschirmfoto 2021-12-06 um 09 50 12](https://user-images.githubusercontent.com/3884521/144815860-edf7637b-5ff7-474f-b791-a74f3735ed42.png)

The main _variables.scss is not imported. And the images-directory referenced in _leaflet.scss is missing.

**Comment by krebbi** [comment]
In your SCSS files some other parts are missing too.

This is a screenshot with 
@import "css/soft-ui-dashboard.css"

![Bildschirmfoto 2021-12-10 um 12 52 29](https://user-images.githubusercontent.com/3884521/145570412-f5552927-12a2-4c72-b8e9-044fc3acb8b8.png)

And This is with  
@import '~bootstrap/scss/bootstrap'
@import "soft-ui-dashboard/theme-pro"

![Bildschirmfoto 2021-12-10 um 12 53 51](https://user-images.githubusercontent.com/3884521/145570468-35588fa0-ec2f-4182-9941-a6624eb0369b.png)

**Comment by rarestoma** [comment]
Hi @krebbi,

Can you please give me access to your theme so I can test is and see exactly what happens?

Thank you,
Rares

**Comment by krebbi** [comment]
I sent you an email.

**Comment by rarestoma** [comment]
Hi @krebbi,

I verified now the email but I can't find anything, can you please send it again to rares@creative-tim.com?

Thank you,
Rares

**Comment by rarestoma** [comment]
Hi @krebbi,

Can you please give me the email address that you used to send the information so I can verify?

Thank you,
Rares

**Comment by krebbi** [comment]
the one you gave me here: https://github.com/creativetimofficial/ct-soft-ui-dashboard-pro/issues/30#issuecomment-993285208

**Comment by rarestoma** [comment]
Hi @krebbi,

Also, can you please tell me your email address?

Thank you,
Rares

**Comment by krebbi** [comment]
sk @ datatainment.de

**Comment by marungsha** [comment]
Same error happening to my project also. I had purchased pro version but the zip file seems some missing image files.

**Comment by jaymegordo** [comment]
+1 same issue with the missing image files: 

```console
[26/Apr/2022 14:11:43] "GET /static/assets/css/images/layers-2x.png HTTP/1.1" 404 1970
[26/Apr/2022 14:11:43] "GET /static/assets/css/images/layers.png HTTP/1.1" 404 1961
[26/Apr/2022 14:11:43] "GET /static/assets/css/images/marker-icon.png HTTP/1.1" 404 1976
[26/Apr/2022 14:11:43] "GET /static/assets/img/curved-images/white-curved.jpeg HTTP/1.1" 404 2003
```

**Comment by anthonyscolaro** [comment]
Same issue.  The plugins/pro/images/ directory is missing from the zip that I downloaded with Soft UI Dashboard Pro

✘  sage ./public [f76d5b9794b3bd92310f]
│
├─ ✘ error
│ resolve './soft-ui-dashboard/plugins/pro/images/layers.png' in './resources/styles'
│   using description file: ./package.json (relative path: ./resources/styles)
│     using description file: ./package.json (relative path: ./resources/styles/soft-ui-dashboard/plugins/pro/images/layers.png)
│       no extension
│         ./resources/styles/soft-ui-dashboard/plugins/pro/images/layers.png doesn't exist
│       .mjs
│         ./resources/styles/soft-ui-dashboard/plugins/pro/images/layers.png.mjs doesn't exist
│       .js
│         ./resources/styles/soft-ui-dashboard/plugins/pro/images/layers.png.js doesn't exist
│       .jsx
│         ./resources/styles/soft-ui-dashboard/plugins/pro/images/layers.png.jsx doesn't exist
│       .css
│         ./resources/styles/soft-ui-dashboard/plugins/pro/images/layers.png.css doesn't exist
│       .json
│         ./resources/styles/soft-ui-dashboard/plugins/pro/images/layers.png.json doesn't exist
│       .wasm
│         ./resources/styles/soft-ui-dashboard/plugins/pro/images/layers.png.wasm doesn't exist
│       .yml
│         ./resources/styles/soft-ui-dashboard/plugins/pro/images/layers.png.yml doesn't exist
│       .scss
│         ./resources/styles/soft-ui-dashboard/plugins/pro/images/layers.png.scss doesn't exist
│       .sass
│         ./resources/styles/soft-ui-dashboard/plugins/pro/images/layers.png.sass doesn't exist
│       as directory
│         ./resources/styles/soft-ui-dashboard/plugins/pro/images/layers.png doesn't exist
│
├─ ✘ error
│ resolve './soft-ui-dashboard/plugins/pro/images/layers-2x.png' in './resources/styles'
│   using description file: ./package.json (relative path: ./resources/styles)
│     using description file: ./package.json (relative path: ./resources/styles/soft-ui-dashboard/plugins/pro/images/layers-2x.png)
│       no extension
│         ./resources/styles/soft-ui-dashboard/plugins/pro/images/layers-2x.png doesn't exist
│       .mjs
│         ./resources/styles/soft-ui-dashboard/plugins/pro/images/layers-2x.png.mjs doesn't exist
│       .js
│         ./resources/styles/soft-ui-dashboard/plugins/pro/images/layers-2x.png.js doesn't exist
│       .jsx
│         ./resources/styles/soft-ui-dashboard/plugins/pro/images/layers-2x.png.jsx doesn't exist
│       .css
│         ./resources/styles/soft-ui-dashboard/plugins/pro/images/layers-2x.png.css doesn't exist
│       .json
│         ./resources/styles/soft-ui-dashboard/plugins/pro/images/layers-2x.png.json doesn't exist
│       .wasm
│         ./resources/styles/soft-ui-dashboard/plugins/pro/images/layers-2x.png.wasm doesn't exist
│       .yml
│         ./resources/styles/soft-ui-dashboard/plugins/pro/images/layers-2x.png.yml doesn't exist
│       .scss
│         ./resources/styles/soft-ui-dashboard/plugins/pro/images/layers-2x.png.scss doesn't exist
│       .sass
│         ./resources/styles/soft-ui-dashboard/plugins/pro/images/layers-2x.png.sass doesn't exist
│       as directory
│         ./resources/styles/soft-ui-dashboard/plugins/pro/images/layers-2x.png doesn't exist
│
├─ ✘ error
│ resolve './soft-ui-dashboard/plugins/pro/images/marker-icon.png' in './resources/styles'
│   using description file: ./package.json (relative path: ./resources/styles)
│     using description file: ./package.json (relative path: ./resources/styles/soft-ui-dashboard/plugins/pro/images/marker-icon.png)
│       no extension
│         ./resources/styles/soft-ui-dashboard/plugins/pro/images/marker-icon.png doesn't exist
│       .mjs
│         ./resources/styles/soft-ui-dashboard/plugins/pro/images/marker-icon.png.mjs doesn't exist
│       .js
│         ./resources/styles/soft-ui-dashboard/plugins/pro/images/marker-icon.png.js doesn't exist
│       .jsx
│         ./resources/styles/soft-ui-dashboard/plugins/pro/images/marker-icon.png.jsx doesn't exist
│       .css
│         ./resources/styles/soft-ui-dashboard/plugins/pro/images/marker-icon.png.css doesn't exist
│       .json
│         ./resources/styles/soft-ui-dashboard/plugins/pro/images/marker-icon.png.json doesn't exist
│       .wasm
│         ./resources/styles/soft-ui-dashboard/plugins/pro/images/marker-icon.png.wasm doesn't exist
│       .yml
│         ./resources/styles/soft-ui-dashboard/plugins/pro/images/marker-icon.png.yml doesn't exist
│       .scss
│         ./resources/styles/soft-ui-dashboard/plugins/pro/images/marker-icon.png.scss doesn't exist
│       .sass
│         ./resources/styles/soft-ui-dashboard/plugins/pro/images/marker-icon.png.sass doesn't exist
│       as directory
│         ./resources/styles/soft-ui-dashboard/plugins/pro/images/marker-icon.png doesn't exist

**Comment by groovemen** [comment]
Hello,

**Comment by groovemen** [comment]
Hello,

Thank you for using our product and sorry for this late response. We have searched for this issue and noticed that it's triggered by this file: `./assets/scss/soft-ui-dashboard/plugins/pro/_leaflet.scss` from line **366**.

Please add the attached folder of images to your project and fix the path to them. Sorry for this inconvenience, we'll fix this issue in the next product update.

[images.zip](https://github.com/creativetimofficial/ct-soft-ui-dashboard-pro/files/9914245/images.zip)

Hope this information helps you. Please let us know if we can help you with anything else.

All the best,
Stefan
