### ISSUE TITLE
[Bug] Sidenav elements over modal windows

### ISSUE THREAD

**Issue by khellendros74** [creativetimofficial/ct-soft-ui-dashboard-pro#33]
### Version
1.05
### Reproduction link
https://ippbx.agencetelecom.tel/support/guide/phone/yealink/t57w
### Operating System
windows
### Device
dell xp 13
### Browser & Version
firefox
### Steps to reproduce
sigin
clic notice (bluebutton)
may need to shrink width of the browser between sm and md i think
### What is expected?
modal over main design window
### What is actually happening?
Some menu elements are over modal window

---
### Solution
/assets/css/soft-ui-dashboard.css
.sidenav {
  z-index: 1035;
}

### Additional comments
refering to this documentation
https://getbootstrap.com/docs/5.0/layout/z-index/
modal backdrop should be over 1040
without z-index it also failded

**Comment by khellendros74** [comment]
For a quick visual with
.sidenav { z-index: 9999; }
![image](https://user-images.githubusercontent.com/46758125/147358328-c076cbaa-bfba-4775-9b7e-06a7d288883f.png)

**Comment by rarestoma** [comment]
Hi @khellendros74,

Thank you for working with our products.

Can you please give me the code that you used so I can test it and see what happens?

Thank you,
Rares

**Comment by khellendros74** [comment]
it s the standard bootstrap 5 modal 
https://getbootstrap.com/docs/5.0/components/modal/
and within your standard lib distribution
`<script src="/assets/js/core/bootstrap.min.js"></script>
`

from my code 
view-source:https://ippbx.agencetelecom.tel/support/guide/phone/yealink/t57w
line: 577/601 Modal declaration
`	
	<div class="modal fade" id="guideModal" tabindex="-1" role="dialog" aria-labelledby="guideModal" aria-hidden="true" data-bs-backdrop="static">
	  <div class="modal-dialog modal-dialog-centered modal-xl" role="document">
		<div class="modal-content">
		  <div class="modal-header">
		    <span class="modal-title text-gradient text-info text-uppercase text-lg font-weight-bold mb-4">Yealink SIP-T57W</span>
			<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
			  <span aria-hidden="true">&times;</span>
			</button>
		  </div>
		  <div class="modal-body">
		  </div>
		  <div class="modal-footer">
			  <a href="/media/guide/Guide_d'utilisation_Yealink T57W_202111.pdf" target="_blank" class="btn btn-icon bg-gradient-info d-lg-block">
				<i class="far fa-file-pdf me-1" aria-hidden="true"></i>
				Télécharger
				<i class="fad fa-external-link ms-1" aria-hidden="true"></i>
			  </a>
			<button type="button" class="btn bg-gradient-secondary" data-bs-dismiss="modal">Fermer</button>
		  </div>
		</form>
		</div>
	  </div>
	</div>
	
`
line: 684/687 Modal instantiation
`	var guideModal = new bootstrap.Modal(document.getElementById('guideModal'), {
		keyboard: true
		, focus: true
	});
`
line: 691 Modal Show
`guideModal.show();
`

if this is what you ask for ?

**Comment by prey87** [comment]
Same in your example
https://demos.creative-tim.com/soft-ui-dashboard-pro/pages/pages/sweet-alerts.html

**Comment by groovemen** [comment]
Hello there,

Thank you for using our products and for letting us know about this issue. Until the next product update we'll ask you to make the following change:
- update the **z-index** property for the `.swal2-container` class 
```
.swal2-container {
    z-index: 9999; 
}
```

Hope this information helps you. Please let us know if we can help you with anything else.

All the best,
Stefan

**Comment by prey87** [comment]
Hey @groovemen,
this is only a little fix but not the solution for the whole problem.

It's the same with Boostrap model's as @khellendros74 already wrote.

In assets/scss/soft-ui-dashboard/_variables.scss is
$zindex-modal:                      1050 !default;

and the default value from Bootstrap (assets/scss/soft-ui-dashboard/bootstrap/_variables.scss) is
$zindex-modal:                      1055 !default;

Maybe I'm wrong, but I think the problem is deeper and needs more investigation.

**Comment by groovemen** [comment]
Hello again, 

We have updated the product and fixed this issue. 
Cheers,
Stefan
