### ISSUE TITLE
[Bug] borken tag <input type="file" /> with inline label

### ISSUE THREAD

**Issue by khellendros74** [creativetimofficial/ct-soft-ui-dashboard-pro#34]
### Version
1.0.5
### Reproduction link
https://codepen.io/khellendros74/pen/eYGKRoN
### Operating System
Windows 10
### Device
Dell XPS 13
### Browser & Version
Firefox 95.0.2 64Bit
### Steps to reproduce
load the reproduction page
### What is expected?
Horizontal border line between elements should be align
### What is actually happening?
border are broken
![image](https://user-images.githubusercontent.com/46758125/148241605-20d4de77-5c46-422d-9a6b-c2939e5937c2.png)

---

**Comment by groovemen** [comment]
Hello @khellendros74, 

Thank you for using our products, you can easily fix this issue (until the next product update) by setting a `margin-bottom: 0;` for the **input-group-text** that will look like this: 

```
<div class="input-group mb-3">
  <label class="input-group-text mb-0" for="inputGroupFile02">Upload</label>
  <input type="file" class="form-control" id="inputGroupFile02" onfocus="focused(this)" onfocusout="defocused(this)">
</div>
```

Hope this information helps you. Please let us know if we can help you with anything else.

All the best,
Stefan
