### ISSUE TITLE
[Bug] Nav-Wrapper horizontal alignment on small screens

### ISSUE THREAD

**Issue by Christian-Ackermann** [creativetimofficial/ct-soft-ui-dashboard-pro#35]
### Version
1.0.5
### Reproduction link
https://demos.creative-tim.com/soft-ui-dashboard-pro/pages/pages/profile/overview.html
### Operating System
Mac Os
### Device
MacBook
### Browser & Version
Chrome 97.0.4692.71
### Steps to reproduce
When you open the site in "mobile" / "responsive" view the navigation elements are oriented horizontally, after you resize the window the elements are changed to a vertical orientation.
### What is expected?
Vertical orientation from the beginning.
### What is actually happening?
Elements are only changing there orientation if you resize the window.

---

**Comment by rarestoma** [comment]
Hi @Christian-Ackermann,

Thank you for working with our products.

We also include vertical tabs for all screens, please see our example in the documentation: https://www.creative-tim.com/learning-lab/bootstrap/navs/soft-ui-dashboard#vertical-tabs

I hope it helps.

Best regards,
Rares

**Comment by Christian-Ackermann** [comment]
Hi @rarestoma, sorry for the late reply. :(

I already knew about the vertical tabs, but I think it's still a bug .... When you open the page mentioned above and switch to "responsive view" the tabs are oriented horizontally, after you resize the page the tabs are automatically aligned vertical. I assume the vertical orientation on mobile devices should be displayed from the beginning isn't it?

Thanks, Christian

**Comment by rarestoma** [comment]
Hi @Christian-Ackermann,

Yes, you are right, I saw now that the tabs are horizontal when opened from mobile. I just added to fix this in the next update.

Thank you,
Rares

**Comment by groovemen** [comment]
Hello @Christian-Ackermann, 

Thank you for using our products, we have fixed the issue that you have mentioned above. To solve it, we'll ask you to replace the product's Javascript file with the following one: 
[soft-ui-dashboard.js.zip](https://github.com/creativetimofficial/ct-soft-ui-dashboard-pro/files/8416269/soft-ui-dashboard.js.zip)
Also we will release a new product update and you can download again the product. 
Hope this information helps you. Please let us know if we can help you with anything else.

All the best,
Stefan
