### ISSUE TITLE
[Bug] Why is the effect I saw in live preview Pro different from that I bought and downloaded?

### ISSUE THREAD

**Issue by shuidiyoushu** [creativetimofficial/ct-soft-ui-dashboard-pro#37]
### Version
1.0.7
### Reproduction link
https://demos.creative-tim.com/soft-ui-dashboard-pro/pages/dashboards/default.html?_ga=2.125142729.2100607776.1642656030-1503550238.1642656030
### Operating System
win10
### Device
All devices
### Browser & Version
Chrome
### Steps to reproduce
I found messages and corresponding solutions in the bug, but I found that there was no corresponding file in the content I downloaded through Pro.
assets/scss/soft-ui-dashboard/_navbar-vertical-extend.scss
### What is expected?
Inconsistent with the preview Pro page display
### What is actually happening?
Why is the effect I see in preview Pro different from the effect I download by purchasing pro? Where should I download the latest version?

---

**Comment by shuidiyoushu** [comment]
![微信图片_20220123102559](https://user-images.githubusercontent.com/69995892/150662545-994d6f58-9e64-4fb2-80bd-f21b9ab236ac.png)
![微信图片_20220123102604](https://user-images.githubusercontent.com/69995892/150662549-38ea8a14-c580-4759-9e2f-6b244af761d7.png)

**Comment by groovemen** [comment]
Hello @shuidiyoushu,

Thank you for using our products, please let us know about what animation you are talking about. 
We have fixed the sidebar overleaping the main content bug into the last update.
Please let us know if we can help you with anything else.

All the best,
Stefan
