### ISSUE TITLE
[Bug] Copy the template to show that the corresponding file cannot be found

### ISSUE THREAD

**Issue by shuidiyoushu** [creativetimofficial/ct-soft-ui-dashboard-pro#38]
### Version
1.0.7
### Reproduction link
http://none
### Operating System
win10
### Device
All devices
### Browser & Version
Chrome
### Steps to reproduce
Copy the template to show that the corresponding file cannot be found
### What is expected?
compiling
### What is actually happening?
not compiling

---
### Additional comments
![微信图片_20220123104713](https://user-images.githubusercontent.com/69995892/150662799-b9bcd8fd-8a49-4f39-8a6f-959f5bba36ad.png)

**Comment by rarestoma** [comment]
Hi @shuidiyoushu,

Thank you for working with our products.

Can you please give me more details about this issue? What is the page that shows this error?

Thank you,
Rares
