### ISSUE TITLE
Scrollbar on minimized Menu in Windows

### ISSUE THREAD

**Issue by krebbi** [creativetimofficial/ct-soft-ui-dashboard-pro#41]
Doesn't look that good right now..
![Bildschirmfoto 2022-04-12 um 18 26 32](https://user-images.githubusercontent.com/3884521/163010170-a3f703c2-b6cf-45ce-a8cc-2dba7dc37a2b.png)

**Comment by krebbi** [comment]
whatever…

**Comment by groovemen** [comment]
Hello @krebbi, 

Thank you for using our products, please let us know which product are you using, also the version of it and the browser on which you have tested. We have tested the HTML version: https://demos.creative-tim.com/soft-ui-dashboard-pro/pages/dashboards/default.html and is working as expected.
All the best, 
Stefan

**Comment by krebbi** [comment]
Hi Stefan,

thanks for your reply. It happens with https://demos.creative-tim.com/vue-soft-ui-dashboard-pro/#/dashboards/dashboard-default on Windows 10 & Firefox (Version 99), Edge (Version 100.0.1185.39), Chrome (Version 100.0.4896.88)

**Comment by sajadevo** [comment]
> Hi Stefan,
> 
> thanks for your reply. It happens with https://demos.creative-tim.com/vue-soft-ui-dashboard-pro/#/dashboards/dashboard-default on Windows 10 & Firefox (Version 99), Edge (Version 100.0.1185.39), Chrome (Version 100.0.4896.88)

**Hi @krebbi,**

Thanks for using our product, just put the following code to the scss file: `::-webkit-scrollbar": { display: "none" }` it will fix the issue and we will fix it by default for the next update of the product.

**All the best**
**Sajad**
