### ISSUE TITLE
[Bug] Form input groups broken since 1.0.8

### ISSUE THREAD

**Issue by lucasnetau** [creativetimofficial/ct-soft-ui-dashboard-pro#42]
### Version
1.0.8
### Reproduction link
https://www.creative-tim.com/
### Operating System
Any
### Device
Any
### Browser & Version
Any
### Steps to reproduce
Version 1.0.8 introduced changes to input-group-text and form-control css classes that override definition higher up in the CSS, these change position of input-group-text to absolute from flex and various other changes including new focused highlights and border changes incompatible with input-group

+.input-group-text {
+  position: absolute;
+  z-index: 9999;
+  height: 100%;
+  border-right: 0;
+  padding-left: 10px;
+  padding-right: 10px;
+  margin-left: -1px;
+}
+
+.input-group-text+.form-control {
+  padding-left: 35px !important;
+}
+
+.form-control {
+  border-radius: 0.5rem;
+  border-top-left-radius: 0.5rem !important;
+  border-bottom-left-radius: 0.5rem !important;
+  border-left-width: 1px;
+}
+
+.focused {
+  box-shadow: 0 0 0 2px #e9aede;
+  transition: box-shadow 0.15s ease, border-color 0.15s ease;
+}
+
+.focused .form-control:focus {
+  box-shadow: none;
+}
+
+.focused .input-group-text {
+  border-color: #e293d3;
+}
+

### What is expected?
Input group text should work with dynamic spaced text
### What is actually happening?
input group text is compatible with input-group

---
### Solution
Revert the change
### Additional comments
There is no reference to these changes in the changelog for 1.0.8. Version 1.0.7 is working fine.

Also how do you expect customers to provide JSFiddle reproductions when you cannot link to a pro css file?!

**Comment by lucasnetau** [comment]
Version 1.0.7 
<img width="977" alt="v1 0 7" src="https://user-images.githubusercontent.com/9331242/163076866-ce945892-2a18-4962-8b54-5e39ab77e158.png">

Version 1.0.8. Note the inputs do not line up due to input-group-text is now position:absolute and input has a hardcoded 35px padding. Focus has been changed to include input-group-text

<img width="980" alt="v1 0 8" src="https://user-images.githubusercontent.com/9331242/163076873-52725b3f-27e4-408d-a0b9-bbe49aec4a88.png">

**Comment by waamtech81** [comment]
Hello Team,
I am also facing the same issue please see the attached file and could you tell me how I will solve this?
Thanks
Reference Link: https://www.awesomescreenshot.com/image/26098257?key=f9d69166affdb3e9fdb84056c4b7942d

**Comment by groovemen** [comment]
Hello there!

We find out a solution to fix this issue so we will ask you to make the following changes until the next product update:

- go to `assets/scss/soft-ui-dashboard/forms/_input-group.scss` and replace it with the file from below:
[_input-group.scss.zip](https://github.com/creativetimofficial/ct-soft-ui-dashboard-pro/files/8572834/_input-group.scss.zip)

Hope this information helps you. Please let us know if we can help you with anything else.

All the best,
Stefan

**Comment by Eonasdan** [comment]
Slightly related. I can open a new issue if needed. The appended version does not work correctly. This icon should be end of the input not at the start.

![image](https://user-images.githubusercontent.com/1006516/186995334-049850fe-8922-496d-ad73-b3781e8efc77.png)

**Comment by groovemen** [comment]
Hello @Eonasdan,

Thank you for letting us know about this issue. We'll add this issue on the TO DO list for the next product update. 
Until then you can simply add the **end-0** class for the `.input-group-text` span like this: 
```
<div class="input-group mb-3">
    <input type="text" class="form-control" placeholder="Recipient's username" aria-label="Recipient's username" aria-describedby="basic-addon2" onfocus="focused(this)" onfocusout="defocused(this)">
    <span class="input-group-text end-0">@example.com</span>
</div>
```

Please let us know if we can help you with anything else.

All the best,
Stefan
