### ISSUE TITLE
The header overlaps the menu on mobile display.

### ISSUE THREAD

**Issue by ach2** [creativetimofficial/ct-soft-ui-dashboard-pro#5]
![image](https://user-images.githubusercontent.com/12981001/123914930-93575880-d99d-11eb-974c-243b38013097.png)

**Comment by rarestoma** [comment]
Hi @ach2,

Thank you for working with our products and for pointing us this issue.

Please replace the z-index for the sidenav from `assets/scss/soft-ui-dashboard/_navbar-vertical-extend.scss` file from `990` to `9999` value.

I also added it to the 'to do' list for the next update.

Best regards,
Rares

**Comment by shuidiyoushu** [comment]
This file was not found. Has it been updated?

**Comment by shuidiyoushu** [comment]
> 嗨@ach2，
> 
> 感谢您使用我们的产品并向我们指出此问题。
> 
> 请将侧导航的 z 索引从文件从 替换为值。`assets/scss/soft-ui-dashboard/_navbar-vertical-extend.scss``990``9999`
> 
> 我还将其添加到下一次更新的"待办事项"列表中。
> 
> 最好的问候，稀有

This file was not found. Has it been updated?

**Comment by rarestoma** [comment]
Hi @shuidiyoushu,

Thank you for working with our products.

Can you please tell me what version are you using?

Thank you,
Rares
