### ISSUE TITLE
[Bug] Requesting refund

### ISSUE THREAD

**Issue by JigarPrajpati** [creativetimofficial/ct-soft-ui-dashboard-pro#50]
### Version
latest
### Reproduction link
https://localhost:7151/
### Operating System
window
### Device
chrome
### Browser & Version
latest
### Steps to reproduce
You can see in my previous message, chart not working property in .net core app, i requesting refund, not going to move ahead with the product.
Thanks
### What is expected?
refund
### What is actually happening?
refund

---

**Comment by dragosct** [comment]
@JigarPrajpati! Please give us your order id.

**Comment by JigarPrajpati** [comment]
191923558
![image](https://user-images.githubusercontent.com/91531559/191699801-769082e6-625a-475b-8a37-54bebfa2d566.png)

**Comment by JigarPrajpati** [comment]
Heloo, dear did you refund it?

**Comment by dragosct** [comment]
Hi, @JigarPrajpati! Yes, you should receive the money soon. 

Regards,
Dragos
