### ISSUE TITLE
Chat on mobile devices is unusable

### ISSUE THREAD

**Issue by Navorski** [creativetimofficial/ct-soft-ui-dashboard-pro#54]
https://demos.creative-tim.com/soft-ui-dashboard-pro/pages/pages/messages.html

This document if you look at this on a mobile device, it is simply unusable.

**Comment by Navorski** [comment]
![image](https://user-images.githubusercontent.com/7352877/210959169-72894de2-b890-4676-8c78-8ebd3424e4ae.png)

**Comment by groovemen** [comment]
Hello @Navorski,

Thank you for using our products and for letting us know about this issue. Until the next product update, we'll ask you to make the following changes: 

- `<div class="col-4"> `will transform to this: `<div class="col-12 col-lg-4">`
- `<div class="col-8"> `will transform to this: `<div class="col-12 col-lg-8">`

or you can just replace your file with the following:
[messages.html.zip](https://github.com/creativetimofficial/ct-soft-ui-dashboard-pro/files/10359319/messages.html.zip)

Please let us know if we can help you with anything else.
All the best,
Stefan
