### ISSUE TITLE
[Bug] Sidebar in dark theme changes to white when resizing 

### ISSUE THREAD

**Issue by filippotoso** [creativetimofficial/ct-soft-ui-dashboard-pro#56]
### Version
Latest version (and demo on your site)
### Reproduction link
https://demos.creative-tim.com/soft-ui-dashboard-pro/pages/ecommerce/referral.html
### Operating System
Windows
### Device
PC
### Browser & Version
Chrome 112.0.5615.121
### Steps to reproduce
1. Open the page https://demos.creative-tim.com/soft-ui-dashboard-pro/pages/ecommerce/referral.html
2. Switch to dark theme
3. Resize the page horizontally untill the sidebar disappers
4. Click on the icon to show the sidebar

See a similar behaviour here: https://youtu.be/LnP_dSPiezM
### What is expected?
The sidebar must keep the dark theem
### What is actually happening?
The sidebar changes to white theme.
Here's a video demostrating the issue:
https://youtu.be/LnP_dSPiezM

---

**Comment by groovemen** [comment]
Hello @filippotoso,

Thank you for using our products and for letting us know about this issue - also, sorry for this late response.
We'll solve this issue in the next product update but until then you can make the following changes to solve it:

- go to `./assets/scss/soft-ui-dashboard/_dark-version.scss` and change the `background: $white !important;` from the **line 27**
- recompile the SCSS after the changes

Hope this information helps you. Please let us know if we can help you with anything else.
All the best,
Stefan

**Comment by filippotoso** [comment]
Change it into what?

**Comment by filippotoso** [comment]
For those who need it:

```css
      background: #111322 !important;
```

**Comment by groovemen** [comment]
Hello again,

Sorry for the confusion, you can simply delete that line `background: $white !important;`

Cheers,
Stefan
