### ISSUE TITLE
Nav-Wrapper

### ISSUE THREAD

**Issue by ghost** [creativetimofficial/ct-soft-ui-dashboard-pro#6]
![image](https://user-images.githubusercontent.com/36150625/124362655-9ae55e80-dc36-11eb-9c96-d2fca1f8e9eb.png)

los estilos del nav-wrapper no funcionan correctamente, alguna idea de que puede estar sucediendo?

![image](https://user-images.githubusercontent.com/36150625/124362643-8acd7f00-dc36-11eb-8479-3b506a92bd02.png)

Thanks!

**Comment by groovemen** [comment]
Hello @SrGiiL,

Thank you for using our products, please give us more details about how we can reproduce this issue? or where can we find it?!
Please let us know if we can help you with anything else.

All the best,
Stefan

**Comment by SrGiiL** [comment]
Hello @groovemen, 

Thanks for response.

I have problem at these route
https://www.ruum.es/property/60ac95ae1102f0b70d348484

auth: Owner (CaseSensitive)
password: 123asd

![image](https://user-images.githubusercontent.com/36150625/124581747-abbdec00-de51-11eb-9b38-d8c4453cbcb8.png)

I test with imports of allmost all libraries but it still not working.

Best,
Daniel
