### ISSUE TITLE
Notification drowpdown

### ISSUE THREAD

**Issue by SrGiiL** [creativetimofficial/ct-soft-ui-dashboard-pro#8]
Hi!

At dropdown notification nav-item with widht less than 1000px, it's looks like in the following image 

![image](https://user-images.githubusercontent.com/36150625/124603048-d025c280-de69-11eb-894b-14128abcd99f.png)

Thanks!

**Comment by groovemen** [comment]
Hello @SrGiiL,

Thank you for using our products, and also for letting us know about this issue. Until the next product update, we'll ask you to change the following file: 

- you have to overwrite the `assets/scss/soft-ui-dashboard/dropdown.scss` with the one from below:
[_dropdown.scss.zip](https://github.com/creativetimofficial/ct-soft-ui-dashboard-pro/files/6770741/_dropdown.scss.zip)
- after that, don't forget to recompile the SCSS, to get the changes in the CSS file.

Hope this information helps you. Please let us know if we can help you with anything else.

All the best,
Stefan

**Comment by SrGiiL** [comment]
Works properly, thanks!
